version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - REDIS_URL=redis://redis:6379
      - API_KEYS=${API_KEYS:-demo-key-123}
      - ALLOWED_ORIGINS=http://localhost:3000,https://yourdomain.com
    depends_on:
      - redis
    volumes:
      - .:/app  # Hot reload for development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: